version: '3'
services:
  server:
    image: server:latest
    ports:
      - "8081:80"
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    image: client:latest
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLIENT_ID=1
  client2:
    image: client:latest
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLIENT_ID=2
  client3:
    image: client:latest
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLIENT_ID=3
